name: Github actions dotnetConsole

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/moses-linux

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Moses Up
      run: |
        echo "${{ github.workspace }}" >> $GITHUB_PATH
        sudo apt-get update
        sudo apt-get install libexpat1
        sudo chmod +x moses
        sudo chmod +x tdskt
        sudo ./moses &
        sleep 15
    -
      name: EULA Accept
      run: |
        sudo ./tdskt platforms
        sudo ./tdskt eula nxp-la-opt-v5 setprop accepted true
        sudo ./tdskt platforms
    -
      name: Enable Emulation
      run: |
        ./tdskt -p enableemulation
    -
      name: Load Application
      run: |
        APPID=$(./tdskt load ../appconfig_0/)
        echo "APPID=$APPID" >> $GITHUB_ENV
    -
      name: Build Application
      run: |
        cd ..
        ls
        docker run --rm -t -v ${PWD}:/workspaces/dotnetConsole --env-file \ 
        ./appconfig_0/containerEnv mcr.microsoft.com/dotnet/sdk:6.0 bash -c \
        "cd /workspaces/dotnetConsole && dotnet build ./dotnetConsole.csproj && dotnet publish -r linux-arm -o ./appconfig_0/work/dotnetConsole ./dotnetConsole.csproj"
    -
      name: Run application
      run: |
        cd ..
        ./moses-linux/tdskt -p application ${{ env.APPID }} build release
